[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
# Node 20 사용
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install"]

[build.nixpacksPlan.phases.build]
# 따로 빌드할 거 없어서 비워둠
cmds = []

[deploy]
startCommand = "npm run bot"
